// The Seeker school's curriculum — the SAME lessons the website teaches, bundled.
//
// ─────────────────────────────────────────────────────────────────────────────────────────────
// WHERE THIS COMES FROM, AND WHY IT IS NOT A SECOND COPY OF THE CURRICULUM
// ─────────────────────────────────────────────────────────────────────────────────────────────
// data/curriculum.json is GENERATED by scripts/extract-curriculum.js, which slices the lesson
// array literals straight out of src/App.jsx (LESSONS, INCUBATOR_LESSONS), src/sections/LPLab.jsx
// (LP_LESSONS) and src/sections/Library.jsx with a balanced-bracket, string-aware extractor. So
// the phone school and the desktop school read the same words, and editing a lesson in one place
// updates both. Nobody retypes a curriculum.
//
// ⚠️ Regenerate after editing lesson data: `node scripts/extract-curriculum.js`. CI's
// curriculum count-drift guard already fails when the counts move without the data being rebuilt.
//
// BUNDLED, NOT FETCHED. ~236KB raw / ~55KB gzipped, inlined by Vite. That is a deliberate trade:
// it makes the whole school work with no connection at all, which is worth real bundle size on a
// phone. Learning is the part of this product that should never depend on signal — the tools need
// the chain, the school does not.
//
// ⚠️ The quiz answers are in here, and that is not a regression of the `/curriculum` removal.
// That page was removed for laying out every lesson body AND its questions and answers on one
// readable screen. The answer key has always shipped inside the website's JS bundle too (LESSONS
// carries `correct` on every question), so bundling it here exposes nothing new. What must not
// come back is a rendered page that reads the key out to anyone who loads it.

import raw from "../../../data/curriculum.json";

// Courses in teaching order, beginner first. The generator emits them in source order, which is
// not the order a learner should meet them — someone new should land on the basics, not on the
// sixteen-lesson fundamentals track.
const ORDER = ["basics", "fundamentals", "lp", "deepdive"];

// The generator's own ids are terse. These are what a person reads, and they go through t() at
// the render site (data is not translated here — i18n.js machine-translates rendered lesson prose
// the same way it does on the website).
const COURSE_META = {
  basics: { label: "The Incubator", sub: "Start here. No wallet, no jargon, no catch." },
  fundamentals: { label: "School of Hard Knocks", sub: "The real curriculum, Freshman to Emeritus." },
  lp: { label: "LP Lab", sub: "How liquidity actually works, and how it takes your money." },
  deepdive: { label: "Deep Dive", sub: "The advanced material, once the rest makes sense." },
};

export const COURSES = ORDER.filter((id) => raw.courses.some((c) => c.id === id)).map((id) => {
  const c = raw.courses.find((x) => x.id === id);
  return {
    id: c.id,
    icon: c.icon || "📘",
    title: COURSE_META[id] ? COURSE_META[id].label : c.title,
    sub: COURSE_META[id] ? COURSE_META[id].sub : c.blurb || "",
    lessons: (c.lessons || []).map((l) => ({
      id: l.id,
      title: l.title,
      icon: l.icon || "•",
      belt: l.belt || "",
      intro: l.intro || "",
      concepts: Array.isArray(l.concepts) ? l.concepts : [],
      questions: Array.isArray(l.questions) ? l.questions : [],
    })),
  };
});

export const TOTAL_LESSONS = COURSES.reduce((n, c) => n + c.lessons.length, 0);

export function courseById(id) {
  return COURSES.find((c) => c.id === id) || null;
}

export function lessonById(courseId, lessonId) {
  const c = courseById(courseId);
  if (!c) return null;
  return c.lessons.find((l) => l.id === lessonId) || null;
}

// ── progress ────────────────────────────────────────────────────────────────────────────────
// `clkn_completed` is the SAME localStorage key the website school uses, so the two agree about
// what "done" means even though a Capacitor webview has its own origin and cannot share the
// value. The durable record is the server ledger, keyed by the anonymous sid — see src/track.js.
const DONE_KEY = "clkn_completed";

export function completedIds() {
  try {
    const v = JSON.parse(localStorage.getItem(DONE_KEY) || "[]");
    return Array.isArray(v) ? v.filter((x) => typeof x === "string") : [];
  } catch (_) {
    return [];
  }
}

export function isDone(id) {
  return completedIds().indexOf(id) !== -1;
}

/** Record a pass locally. The server beacon is fired by the caller through src/track.js. */
export function markDone(id) {
  try {
    const done = completedIds();
    if (done.indexOf(id) === -1) {
      done.push(id);
      localStorage.setItem(DONE_KEY, JSON.stringify(done.slice(-500)));
    }
  } catch (_) {}
}

export function courseProgress(courseId) {
  const c = courseById(courseId);
  if (!c) return { done: 0, total: 0 };
  const done = completedIds();
  return { done: c.lessons.filter((l) => done.indexOf(l.id) !== -1).length, total: c.lessons.length };
}

/**
 * The next lesson a learner should see: the first unfinished one, walking courses in teaching
 * order. Null when everything is done — the caller shows the finished state rather than a
 * "continue" button that goes nowhere.
 */
export function nextLesson() {
  const done = completedIds();
  for (const c of COURSES) {
    for (const l of c.lessons) {
      if (done.indexOf(l.id) === -1) return { course: c, lesson: l };
    }
  }
  return null;
}
