#!/usr/bin/env node
// Vendor the brand webfonts (Anton, Chakra Petch) into public/vendor/fonts/ and regenerate the
// @font-face block inside public/theme.css. Re-runnable and idempotent: run it again to refresh
// the files or pick up a new Google Fonts revision.
//
// WHY THIS EXISTS. theme.css used to open with:
//   @import url('https://fonts.googleapis.com/css2?family=Anton&family=Chakra+Petch:...');
// which costs us three things that all matter more now that the Seeker app ships to a phone:
//
//   1. OFFLINE. The dApp Store bundle carries its own CSS but the FONTS came off the network, so
//      the brand type vanished the moment the phone lost signal. An app you can open on a plane
//      should not change typeface. Found by scripts/seeker-app-boot-test.cjs, which caught the
//      request leaving the bundle.
//   2. A THIRD PARTY ON EVERY COLD START. A store app that phones fonts.googleapis.com before it
//      renders anything is a privacy surface we get nothing for.
//   3. SPEED. @import is a blocking round trip to one origin that then round-trips to another
//      (gstatic) before a single glyph downloads. Self-hosted, the woff2 fetch starts immediately
//      from the origin that already served the CSS.
//
// WHAT IT DOES NOT CHANGE. Every subset Google serves is vendored — all 19 faces, including thai
// and vietnamese — with the `unicode-range` descriptors copied verbatim. A browser therefore
// downloads exactly the same subsets it downloaded before for any given page, and the rendering
// is identical. This is a change of ORIGIN, not of typography. (Vietnamese is not optional: `vi`
// is one of the school's seven languages.)
//
// Paths are RELATIVE (`vendor/fonts/x.woff2`), which is load-bearing. theme.css is served from
// the site root, so a relative url resolves to /vendor/fonts/... on the web; inside the Capacitor
// bundle the same CSS sits at the bundle root and resolves to <bundle>/vendor/fonts/... . One
// spelling works in both places; an absolute /vendor/... would break the bundle.
//
// Both families are SIL Open Font License 1.1 — see public/vendor/fonts/OFL-NOTICE.txt, which
// this script keeps in step. Self-hosting is explicitly permitted by that licence.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
const FONT_DIR = path.join(ROOT, "public", "vendor", "fonts");
const THEME = path.join(ROOT, "public", "theme.css");

const CSS_URL = "https://fonts.googleapis.com/css2?family=Anton&family=Chakra+Petch:wght@400;500;600;700&display=swap";
// Google serves woff2 only to a browser-shaped UA; ask as one and we get the modern format.
const UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";

const BEGIN = "/* === BEGIN vendored brand fonts — generated by scripts/vendor-fonts.mjs === */";
const END = "/* === END vendored brand fonts === */";

const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");

async function main() {
  const res = await fetch(CSS_URL, { headers: { "User-Agent": UA } });
  if (!res.ok) throw new Error(`font css ${res.status}`);
  const css = await res.text();

  // Split on the subset comments Google emits before each @font-face.
  const faces = [];
  const re = /\/\*\s*([a-z-]+)\s*\*\/\s*@font-face\s*\{([^}]+)\}/g;
  let m;
  while ((m = re.exec(css))) {
    const subset = m[1];
    const body = m[2];
    const pick = (k) => (body.match(new RegExp(k + ":\\s*([^;]+);")) || [, ""])[1].trim();
    const url = (body.match(/url\((https:\/\/fonts\.gstatic\.com\/[^)]+)\)/) || [, ""])[1];
    if (!url) continue;
    faces.push({
      subset,
      family: pick("font-family").replace(/['"]/g, ""),
      style: pick("font-style"),
      weight: pick("font-weight"),
      display: pick("font-display") || "swap",
      unicodeRange: pick("unicode-range"),
      url,
    });
  }
  if (faces.length !== 19) {
    // A count change means Google revved the families. That is not automatically wrong, but it
    // must be a decision someone makes, not something a nightly re-run absorbs silently.
    console.warn(`[vendor-fonts] expected 19 faces, got ${faces.length} — Google may have revved the family. Check before committing.`);
  }

  fs.mkdirSync(FONT_DIR, { recursive: true });
  const out = [];
  for (const f of faces) {
    const name = `${slug(f.family)}-${f.weight}-${f.subset}.woff2`;
    const dest = path.join(FONT_DIR, name);
    const r = await fetch(f.url, { headers: { "User-Agent": UA } });
    if (!r.ok) throw new Error(`${f.url} -> ${r.status}`);
    const buf = Buffer.from(await r.arrayBuffer());
    // woff2 files start with the signature 'wOF2'. A proxy error page written to disk as a font
    // is the failure mode that would ship a broken bundle looking green, so check the bytes.
    if (buf.slice(0, 4).toString("latin1") !== "wOF2") throw new Error(`${name}: not a woff2 (got ${buf.slice(0, 16).toString("latin1")})`);
    fs.writeFileSync(dest, buf);
    out.push({ ...f, name, bytes: buf.length });
  }

  const block = [
    BEGIN,
    "/* Anton + Chakra Petch, SIL OFL 1.1, served from our own origin. Regenerate with",
    "   `node scripts/vendor-fonts.mjs`. unicode-range is copied verbatim from Google's own CSS,",
    "   so each browser still downloads only the subsets it needs and rendering is unchanged. */",
    ...out.map((f) => [
      `@font-face { /* ${f.subset} */`,
      `  font-family: '${f.family}';`,
      `  font-style: ${f.style};`,
      `  font-weight: ${f.weight};`,
      `  font-display: ${f.display};`,
      `  src: url('vendor/fonts/${f.name}') format('woff2');`,
      `  unicode-range: ${f.unicodeRange};`,
      `}`,
    ].join("\n")),
    END,
  ].join("\n");

  let theme = fs.readFileSync(THEME, "utf8");
  if (theme.includes(BEGIN)) {
    theme = theme.replace(new RegExp(BEGIN.replace(/[.*+?^${}()|[\]\\]/g, "\\$&") + "[\\s\\S]*?" + END.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")), block);
  } else {
    const importLine = /@import url\('https:\/\/fonts\.googleapis\.com\/[^']*'\);\n?/;
    if (!importLine.test(theme)) throw new Error("theme.css: no Google Fonts @import and no generated block — refusing to guess where the fonts go");
    theme = theme.replace(importLine, block + "\n");
  }
  fs.writeFileSync(THEME, theme);

  const notice = path.join(FONT_DIR, "OFL-NOTICE.txt");
  let txt = fs.existsSync(notice) ? fs.readFileSync(notice, "utf8") : "";
  if (!/Anton/.test(txt) || !/Chakra Petch/.test(txt)) {
    txt = txt.trimEnd() + `\n\nAnton (https://fonts.google.com/specimen/Anton) and Chakra Petch\n(https://fonts.google.com/specimen/Chakra+Petch) are licensed under the SIL Open Font\nLicense 1.1 (https://scripts.sil.org/OFL), which permits self-hosting. Vendored into this\ndirectory by scripts/vendor-fonts.mjs so the app and the site do not depend on a third\nparty to render their own typography.\n`;
    fs.writeFileSync(notice, txt.trimStart() + "");
  }

  const total = out.reduce((n, f) => n + f.bytes, 0);
  console.log(JSON.stringify({ faces: out.length, bytes: total, kib: Math.round(total / 1024), files: out.map((f) => f.name) }, null, 1));
}
main().catch((e) => { console.error("[vendor-fonts]", e.message); process.exit(1); });
