// Cluck Norris — Seeker app, the Daily pane.
//
// ─────────────────────────────────────────────────────────────────────────────────────────────
// WHAT THIS USED TO BE, AND WHY IT CHANGED (owner, 2026-09-21)
// ─────────────────────────────────────────────────────────────────────────────────────────────
// This was a market screen: majors, trending, gainers, losers, hot pools, new pools, and a
// section headed "Blue-chip LP picks" with a "%/day" yield beside each pair.
//
// Three of this repo's own rules say that cannot ship next to a school:
//   - "picks" is a recommendation, and the brand rule is SAY WHAT'S ON-CHAIN, NEVER WHY;
//   - "blue-chip" is a safety verdict on tokens, which AGENTS.md forbids outright;
//   - a daily YIELD FIGURE is backward-looking fee revenue printed as a rate, before impermanent
//     loss — and the Earn rule is never a yield figure we do not pay.
// The "Informational only — not financial advice" line underneath did not fix any of that. A
// disclaimer under a recommendation is the oldest tell in crypto, and this app teaches people to
// distrust it.
//
// The sharpest version of the problem: the LP Lab teaches impermanent loss and that fee APR is
// not return, and two tabs away we printed a daily yield beside a "pick".
//
// The owner's instinct was right though — someone opening the app daily needs a reason to, and
// the school is finite (58 lessons, then nothing). So the daily habit stays and its CONTENT
// changed: today's lesson, a ten-second check, and market context that is only facts.
//
// KEPT: the majors — prices and 24h change, no verdicts.
// DROPPED: trending, gainers, losers, hot pools, new pools, LP picks — and with them both places
// a yield percentage was rendered.
//
// ⚠️ AND `brief` TOO, WHICH IS WHY THE FIRST VERSION OF THIS FILE DID NOT ACTUALLY FIX ANYTHING.
// The brief is Cluck's written read, generated by `cluckBrief()` in server.js — and its system
// prompt asked, in those words, for "our blue-chip LP yield picks". So the pane deleted the LP
// picks section and then rendered a paragraph generated to contain LP picks. Dropping the fields
// is not enough when a free-text field is built from them (Codex, PR #390).
//
// Two changes, because either alone leaves the claim live somewhere:
//   - this pane no longer renders `payload.brief` at all, and
//   - the prompt in server.js no longer asks for picks or for "blue-chip" anything, and forbids
//     rendering a fee ratio as a yield or a return. That prompt also feeds the public daily
//     Telegram/X post, so leaving it would have meant the brand still says it every day.
//
// ⚠️ SCOPE: this changed the PANE only. `/api/alpha` still returns everything it did, and the
// daily Telegram/X post is untouched — those are separate surfaces and were not part of the ask.
// The dropped fields are simply not read here.
//
// Endpoint (server.js ~5157): GET /api/alpha → { success, generatedAt, date, data: {...}, brief }
// `Cache-Control: public, max-age=600`; the server rebuilds at most every ~20h (ALPHA_TTL), so
// "Refresh" re-reads that cache and never passes ?refresh=1 (which forces a live Claude call).
//
// ⚠️ THE LESSON HALF NEVER FAILS. Today's lesson and its question come from the BUNDLED
// curriculum, so they render with no connection and have no loading or unavailable state. Only
// the market half fetches, and when it is down the lesson is still there — the daily habit must
// not depend on signal.
import React from "react";
import { Link } from "react-router-dom";
import { t, tf, useI18nReady } from "../i18n.js";
import { Pane, Loading, Unavailable, toolFetch, useOnline } from "../pane.jsx";
import { lessonOfDay, questionOfDay, answeredToday, streakCount, recordAnswer } from "../school/daily.js";
import "./tools.css";

function fmtPrice(n) {
  const v = Number(n);
  if (!Number.isFinite(v)) return "?";
  return v >= 1 ? v.toLocaleString(undefined, { maximumFractionDigits: 2 }) : v.toFixed(v < 0.01 ? 6 : 4);
}
function fmtPct(n) {
  const v = Number(n);
  if (!Number.isFinite(v)) return null;
  return (v >= 0 ? "+" : "") + v.toFixed(1) + "%";
}
function pctClass(n) { return Number(n) >= 0 ? "seeker-launch-up" : "seeker-launch-down"; }

function Section({ title, children }) {
  return (
    <section className="seeker-brief-card">
      <h2 className="seeker-brief-card-title">{title}</h2>
      {children}
    </section>
  );
}

// ── the daily check ─────────────────────────────────────────────────────────────────────────
// One question from today's lesson. Answering it is NOT a lesson pass and deliberately sends no
// beacon: the graduation ledger's marks are earned by finishing a real lesson, and letting a
// one-tap answer inflate them would undermine the only anti-farm control in front of a
// treasury-paid diploma.
function DailyCheck() {
  const pick = questionOfDay();
  const [picked, setPicked] = React.useState(null);
  const [streak, setStreak] = React.useState(() => streakCount());
  const [done, setDone] = React.useState(() => answeredToday());

  if (!pick) return null;
  const { q, course, lesson } = pick;
  const answered = picked !== null;
  const right = answered && picked === q.correct;

  function choose(i) {
    if (answered) return;
    setPicked(i);
    if (!done) {
      setStreak(recordAnswer());
      setDone(true);
    }
  }

  return (
    <Section title={t("Today's check")}>
      {done && !answered ? (
        <p className="seeker-tool-note">{t("You've already done today's check. Here it is again — it won't change your streak.")}</p>
      ) : null}

      <p className="seeker-school-q seeker-daily-q">{q.q}</p>

      <div className="seeker-school-options">
        {q.options.map((opt, i) => {
          let cls = "seeker-school-option";
          if (answered && i === q.correct) cls += " correct";
          else if (answered && i === picked) cls += " wrong";
          return (
            <button key={i} type="button" className={cls} onClick={() => choose(i)} disabled={answered}>
              {opt}
            </button>
          );
        })}
      </div>

      {answered ? (
        <div className={"seeker-school-explain" + (right ? " right" : "")}>
          <div className="seeker-school-explain-verdict">{right ? t("Correct.") : t("Not quite.")}</div>
          {q.explanation ? <p>{q.explanation}</p> : null}
          {/* ⚠️ ONE sentence with the value inside, via tf() — never t("Day") + n + t("in a row").
              i18n.js's own header records why: word order differs in six of our seven languages,
              and a translator handed the fragments separately cannot produce a correct sentence. */}
          {streak > 1 ? (
            <p className="seeker-daily-streak">{tf("Day {n} in a row.", { n: streak })}</p>
          ) : null}
          <Link className="seeker-btn" to={`/school/${course.id}/${lesson.id}`}>
            {t("Read the full lesson")}
          </Link>
        </div>
      ) : null}
    </Section>
  );
}

export default function DailyBriefPane() {
  useI18nReady();
  const online = useOnline();
  const [phase, setPhase] = React.useState("loading"); // loading | result | unavailable
  const [payload, setPayload] = React.useState(null);
  const [errKind, setErrKind] = React.useState("unavailable");
  const abortRef = React.useRef(null);

  const today = lessonOfDay();

  const load = React.useCallback(() => {
    setPhase("loading");
    try { abortRef.current && abortRef.current.abort(); } catch (_) {}
    const ctrl = new AbortController();
    abortRef.current = ctrl;
    toolFetch("/api/alpha", { signal: ctrl.signal }).then((res) => {
      if (!res.ok) {
        if (res.kind === "aborted") return;
        setPhase("unavailable");
        setErrKind(res.kind === "offline" ? "offline" : "unavailable");
        return;
      }
      setPayload(res.data);
      setPhase("result");
    });
  }, []);

  React.useEffect(() => {
    load();
    return () => { try { abortRef.current && abortRef.current.abort(); } catch (_) {} };
  }, [load]);

  const d = (payload && payload.data) || {};

  return (
    <Pane icon="📅" title="Daily">
      <p className="seeker-tool-lede">
        {t("One lesson and one question a day, plus where the majors closed. Free, no wallet needed.")}
      </p>

      {/* The lesson half is bundled — it renders before any fetch resolves and survives its failure. */}
      {today ? (
        <Link className="seeker-school-continue seeker-daily-lesson" to={`/school/${today.course.id}/${today.lesson.id}`}>
          <span className="seeker-school-continue-label">{t("Today's lesson")}</span>
          <span className="seeker-school-continue-title">{today.lesson.icon} {today.lesson.title}</span>
        </Link>
      ) : null}

      <DailyCheck />

      <Section title={t("The majors")}>
        {phase === "loading" ? <Loading label={t("Reading the tape…")} /> : null}
        {phase === "unavailable" ? <Unavailable kind={errKind} onRetry={load} /> : null}

        {phase === "result" && payload ? (
          <>
            {(d.majors || []).length ? (
              <div className="seeker-brief-majors">
                {d.majors.map((m) => (
                  <div className="seeker-brief-major" key={m.sym}>
                    <span className="seeker-brief-major-sym">{m.sym}</span>
                    <span className="seeker-brief-major-px">${fmtPrice(m.price)}</span>
                    {m.chg != null ? <span className={pctClass(m.chg)}>{fmtPct(m.chg)}</span> : null}
                  </div>
                ))}
              </div>
            ) : (
              <p className="seeker-tool-note">{t("No prices in today's read.")}</p>
            )}

            {/* ⚠️ `payload.brief` is deliberately NOT rendered — see the header. It is free text
                generated from the same scanner rows this pane drops, so printing it undoes the
                drop. Do not add it back without reading cluckBrief()'s system prompt first. */}
            {payload.date ? <div className="seeker-brief-date">{payload.date}</div> : null}

            <button type="button" className="seeker-btn seeker-btn-quiet seeker-brief-refresh" onClick={load} disabled={!online}>
              {t("Refresh")}
            </button>
          </>
        ) : null}
      </Section>

      <p className="seeker-brief-disclaimer">
        {t("Prices, not advice. Nothing here is a recommendation to buy, sell or provide liquidity.")}
      </p>
    </Pane>
  );
}
